<a href="https://colab.research.google.com/github/Divyanshyadavofficial/NlpWithRNNAndAttention/blob/main/nlpWithRnnsAndAttention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Python >=3.5 is required
import sys
assert sys.version_info >=(3,5)
# Is this notebook running on Colab or Kaggle?
IS_COLAB = "google.colab" in sys.modules
IS_KAGGLE = "kaggle_secrets" in sys.modules

if IS_COLAB:
  %pip install -q -U tensorflow-addons
  %pip install -q -U transformers

# Scikit-Learn >=0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Tensorflow >=2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__>="2.0"
if not tf.config.list_physical_devices('GPU'):
  print("No GPU was detected. CNNs can be very slow without a GPU.")
  if IS_COLAB:
    print("Go to Runtime > Change runtime and select a GPU hardware accelerator.")
  if IS_KAGGLE:
    print("Go to Settings > Accelerator and select GPU.")

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot preety figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes',labelsize=14)
mpl.rc('xtick',labelsize=12)
mpl.rc('ytick',labelsize=12)

# where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "nlp"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR,"images",CHAPTER_ID)
os.makedirs(IMAGES_PATH,exist_ok=True)

def save_fig(fig_id,tight_layout=True,fig_extension="png",resolution=300):
  path = os.path.join(IMAGES_PATH,fig_id+"."+fig_extension)
  print("Saving figure",fig_id)
  if tight_layout:
    plt.tight_layout()
  plt.savefig(path,format=fig_extension,dpi=resolution)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 611.8/611.8 kB 10.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
inflect 7.5.0 requires typeguard>=4.0.1, but you have typeguard 2.13.3 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 120.7 MB/s eta 0:00:00


In [2]:
np.random.seed(42)
tf.random.set_seed(42)

n_steps = 5
dataset = tf.data.Dataset.from_tensor_slices(tf.range(15))
dataset = dataset.window(n_steps,shift=2,drop_remainder=True)
dataset = dataset.flat_map(lambda window:window.batch(n_steps))
dataset = dataset.shuffle(10).map(lambda window:(window[:-1],window[1:]))
dataset = dataset.batch(3).prefetch(1)
for index,(X_batch,Y_batch) in enumerate(dataset):
  print("_"*20,"Batch",index,"\nX_batch")
  print(X_batch.numpy())
  print("="*5,"Y_batch")
  print(Y_batch.numpy())

____________________ Batch 0 
X_batch
[[6 7 8 9]
 [2 3 4 5]
 [4 5 6 7]]
===== Y_batch
[[ 7  8  9 10]
 [ 3  4  5  6]
 [ 5  6  7  8]]
____________________ Batch 1 
X_batch
[[ 0  1  2  3]
 [ 8  9 10 11]
 [10 11 12 13]]
===== Y_batch
[[ 1  2  3  4]
 [ 9 10 11 12]
 [11 12 13 14]]


In [3]:
shakespeare_url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filepath = keras.utils.get_file("shakespeare.txt",shakespeare_url)
with open(filepath) as f:
    shakespeare_text = f.read()

1115394/1115394 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
print(shakespeare_text[:148])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?



In [5]:
"".join(sorted(set(shakespeare_text.lower())))

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [6]:
tokenizer = keras.preprocessing.text.Tokenizer(char_level=True)
tokenizer.fit_on_texts(shakespeare_text)

In [7]:
tokenizer.texts_to_sequences(["First"])

[[20, 6, 9, 8, 3]]

In [9]:
tokenizer.sequences_to_texts([[20,6,9,8,3]])

['f i r s t']

In [10]:
max_id = len(tokenizer.word_index) # number of distinct characters
dataset_size = tokenizer.document_count # total number of characters

In [11]:
[encoded] = np.array(tokenizer.texts_to_sequences([shakespeare_text]))-1
train_size = dataset_size * 90//100
dataset = tf.data.Dataset.from_tensor_slices(encoded[:train_size])

In [12]:
n_steps = 100
window_length = n_steps+1 #target = input shifted one character ahead
dataset = dataset.window(window_length,shift=1,drop_remainder=True)

In [13]:
dataset = dataset.flat_map(lambda window:window.batch(window_length))

In [14]:
np.random.seed(42)
tf.random.set_seed(42)


In [15]:
batch_size = 32
dataset = dataset.shuffle(10000).batch(batch_size)
dataset = dataset.map(lambda windows:(windows[:,:-1],windows[:,1:]))

In [16]:
dataset = dataset.map(
    lambda X_batch,Y_batch:(tf.one_hot(X_batch,depth = max_id),Y_batch)
)

In [17]:
dataset = dataset.prefetch(1)

In [18]:
for X_batch,Y_batch in dataset.take(1):
  print(X_batch.shape,Y_batch.shape)


(32, 100, 39) (32, 100)
